version: '3.1'

networks:
  idp-priv:
  pub:

services:
  beaconprod:
    restart: on-failure
    build:
      context: .
    container_name: beaconprod
    ports:
      - "5050:5050"
    entrypoint: ['python','-m','beacon']
    volumes:
      - ./beacon/logs/logs.log:/beacon/logs/logs.log
      - ./beacon/conf/conf.py:/beacon/conf/conf.py
      - ./beacon/conf/conf_default.py:/beacon/conf/conf_default.py
      - ./beacon/connections/mongo/conf.py:/beacon/connections/mongo/conf.py
      - ./beacon/permissions:/beacon/permissions
      - ./beacon/models:/beacon/models
      - ./beacon/conf/models:/beacon/conf/models
      - ./beacon/__main__.py:/beacon/__main__.py
      - ./beacon/views:/beacon/views
    networks:
      - pub

  admin-ui:
    restart: always
    build:
      context: ./adminui
    container_name: admin-ui
    ports:
      - "3001:3001"
    entrypoint: ['bash','/home/app/web/start.sh']
    volumes:
      - ./beacon:/home/app/web/beacon
      - ./adminui:/home/app/web
    networks:
      - pub
  
  idp:
    image: quay.io/keycloak/keycloak:12.0.0
    #image: sleighzy/keycloak
    hostname: idp
    container_name: idp
    environment:
      # - KEYCLOAK_FRONTEND_URL=http://idp:8080/auth
      # - KEYCLOAK_LOGLEVEL=DEBUG
      # - ROOT_LOGLEVEL=DEBUG
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=secret
      - DB_USER=admin
      - DB_PASSWORD=secret
      - DB_VENDOR=postgres
      - DB_ADDR=idp-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      #- DB_SCHEMA=public
      - KEYCLOAK_IMPORT=/tmp/beacon-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled
      # he modificado esto 
      - KEYCLOAK_HOSTNAME=localhost
      #- KC_HOSTNAME_URL=https://beacon-network-test2.ega-archive.org
      #- KC_HOSTNAME_ADMIN_URL=https://beacon-network-test2.ega-archive.org
      #- KEYCLOAK_FRONTEND_URL=https://beacon-network-test2.ega-archive.org/auth/
      # he modificado esto 
      - KEYCLOAK_FRONTEND_URL=https://localhost/auth
      - PROXY_ADDRESS_FORWARDING=true
    volumes:
      - ./beacon/auth/realms/beacon-realm.json:/tmp/beacon-realm.json
    ports:
      - "8080:8080"
      - "9991:8443"
    networks:
      - idp-priv 
      - pub
    depends_on:
      - idp-db

  idp-db:
    image: postgres
    hostname: idp-db
    container_name: idp-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    networks:
      - idp-priv

  db:
    #image: mongo:5.0.32
    #image: mongo:6.0.27
    image: mongo:7.0.31
    #command: --wiredTigerCacheSizeGB 4
    #command: --wiredTigerCacheSizeGB 4 --sslMode requireSSL --tlsCertificateKeyFile test-server1.pem --tlsCAFile test-ca.pem
    hostname: mongo
    container_name: mongoprod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: beacon
    volumes:
      - ./beacon/connections/mongo/mongo-init/:/docker-entrypoint-initdb.d/:ro
      - ./beacon/connections/mongo/data/:/data
      - ./beacon/connections/mongo/data/db:/data/db
      - ./beacon/connections/mongo/data/configdb:/data/configdb
      - ./beacon/connections/mongo/data/caseLevelData:/data/caseLevelData
      - ./beacon/connections/mongo/mongod.conf:/etc/mongod.conf:ro
      - ./ri-tools/output_docs:/data/output_docs 
      #- ./test-server1.pem:/test-server1.pem
      #- ./test-ca.pem:/test-ca.pem
      #- ./test-client.pem:/test-client.pem
    networks:
      - pub
    command: ["--config", "/etc/mongod.conf"]
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - pub

  beacon-ri-tools:
    image: ghcr.io/ega-archive/beacon2-ri-tools-v2:2.0.6
    hostname: beacon-ri-tools
    container_name: ri-tools
    networks:
      - pub
    tty: true
    volumes:
      - ./ri-tools/output_docs:/usr/src/app/output_docs
      - ./ri-tools/conf:/usr/src/app/conf
      - ./ri-tools/files/vcf/files_to_read:/usr/src/app/files/vcf/files_to_read
      - ./ri-tools/csv:/usr/src/app/csv
      - ./ri-tools/files/updated_json:/usr/src/app/files/updated_json
      - ./ri-tools/pipelines/default/templates:/usr/src/app/pipelines/default/templates

  phenopackets-to-BFF:
    image: ghcr.io/ega-archive/phenopackets-to-bff:latest
    restart: always
    hostname: phenopackets-to-BFF
    container_name: phenopackets-to-BFF
    volumes:
      - ./ri-tools/phenopackets-to-BFF/:/usr/src/app/examples
    networks:
      - pub

  templateUI:
    image: ghcr.io/ega-archive/beacon-template-ui:main
    restart: always
    hostname: template-ui
    container_name: template-ui
    command: node /opt/yarn-v1.22.22/bin/yarn.js start
    ports:
      - 3000:3000
    volumes:
      - ./template-ui/src/config/config.json:/client/src/config/config.json
      - ./template-ui/.env:/client/.env
      - ./template-ui/src:/client/public/assets/logos/
    networks:
      - pub
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
